spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}

deca:
    base-url: ${DECA_BASE_URL}
    directorio-documentos: ${DECA_DOCUMENTOS_DIR:/app/documentos}